before_script:
  - module add  python/3.6.1-2-anaconda
  - pip install --user pytest-pythonpath==0.7.1 pytest-cov==2.5.1
  - module load  nextflow/0.31.0
  
stages:
  - unit
  - download
  - fastqc
  - multiqc
  

download_test:
  stage: download
  only:
  - master
  script:
  - nextflow run workflow/main.nf